### ISSUE TITLE
Come conventions and antipatterns that should be written up.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/snake-charmers-tactical-manual#26]
We should have a section on anti-patterns and conventions.

1. antipatterns
  - return value checking
  - implementing `cls.is_something` as a function since `bool(cls.is_something)` on functions always returns true (they should be `@property` methods).
2. code conventions
  - validation functions -> no return values
3. suggested naming conventions
  - `validate_thing` -> returns `None` or raises a `ValidationError`
  - `normalize_thing` -> returns a thing after some processing
  - `get_thing` -> no side effects
  - `construct_thing` or `build_thing` -> wrappers for constructor/initializor logic
  - `extract_thing` -> pull the data for `thing` out of some more complex data structure.
  - `from_thing` -> normally a `classmethod`, used for alternate ways to initialize an object which may wrap some sort of normalization logic.
  - `is_active` > For use with attributes/properties.  The `is_` prefix removes ambiguity of whether this is a method or not.

**Comment by carver** [comment]
:+1: for most

`get_thing` may be too restrictive. For example: `chain.get_canonical_head()` won't be idempotent. I think I'm on board with no side effects as a recommendation (but things like caching would be reasonable too...).
