### ISSUE TITLE
CLI Conventions

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/snake-charmers-tactical-manual#43]
New standard convention I'd like to add if there is agreement.

original comment: https://github.com/ethpm/ethpm-cli/pull/1#discussion_r274081789

For CLI tools:

- `--full-name`:  Non-abbreviated flags get a double `--` prefix and use single `-` as their word separator.
- `-f`: Alias/abbreviations only use a single `-` prefix
- `-full`: We **don't** do this, using a single `-` prefix for a long name (anyone else find themselves confused when they run across CLI tools that use this format?)

**Comment by cburgdorf** [comment]
100 %

**Comment by ralexstokes** [comment]
+1 -- different tools handle `(single dash, multichar)` differently which is why it is always annoying to handle... i like the obvious symmetry behind `(single dash, single char)`, `(multi dash, multi char)`

**Comment by davesque** [comment]
But `find` does it :).  J/K.  I'm in favor of this 👍 .
